name: Build Windows x64

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Build Windows packages
      id: build-packages
      uses: love-action/love-actions-windows@v1
      with:
        love-package: ./game.love
        # icon-path: ./assets/windows/icon.ico
        # rc-path: ./assets/windows/template.rc
        product-name: Tileman
        # app-id: ${{ secrets.APP_ID }}
        # product-website: https://www.example.com
        installer-languages: English.isl
        output-folder: "./dist"